export const REQUEST_STOCKSYMBOLS = 'REQUEST_STOCKSYMBOLS';
export const RECEIVE_STOCKSYMBOLS = 'RECEIVE_STOCKSYMBOLS';
export const SELECT_STOCKSYMBOL = 'SELECT_STOCKSYMBOL';
export const CHANGE_STOCKSYMBOL = 'CHANGE_STOCKSYMBOL';